import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import  Header from "./header/page";
import  Footer from "./footer/page";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Groups Routing Create Login & Signup Account",
  description: "Generated by Muzna Amir Zubairi",
};

export default function PublicLayout({children}:any){
  return (
    <html>
      <body
       className={`${geistSans.variable} ${geistMono.variable} antialiased`}

      >          
                <Header/>
                {children}
                <Footer/>



      </body>
    </html>








   );
}
